# Specify the minimum perl required
requires 'perl', '5.34.0';

# Generci modules needed
requires 'Net::DNS',      '== 1.31';
requires 'NetAddr::IP',   '== 4.079';
requires 'HTML::Parser',  '== 3.76';
requires 'Inline::C',     '== 0.81';
requires 'File::FindLib', '== 0.001004';

# MailScanner modules needed
requires 'Archive::Tar';
requires 'Archive::Zip';
requires 'bignum';
requires 'Carp';
requires 'Compress::Zlib';
requires 'Compress::Raw::Zlib';
requires 'Convert::BinHex';
requires 'Convert::TNEF';
requires 'Data::Dumper';
requires 'Date::Parse';
requires 'DBD::SQLite';
requires 'DBI';
requires 'Digest::HMAC';
requires 'Digest::MD5';
requires 'Digest::SHA1';
requires 'DirHandle';
requires 'ExtUtils::MakeMaker';
requires 'Fcntl';
requires 'File::Basename';
requires 'File::Copy';
requires 'File::Path';
requires 'File::Spec';
requires 'File::Temp';
requires 'FileHandle';
requires 'Filesys::Df';
requires 'Getopt::Long';
requires 'Inline::C';
requires 'IO';
requires 'IO::File';
requires 'IO::Pipe';
requires 'IO::Stringy';
requires 'HTML::Entities';
requires 'HTML::Parser';
requires 'HTML::Tagset';
requires 'HTML::TokeParser';
requires 'Mail::Field';
requires 'Mail::Header';
requires 'Mail::IMAPClient';
requires 'Mail::Internet';
requires 'Math::BigInt';
requires 'Math::BigRat';
requires 'MIME::Base64';
requires 'MIME::Decoder';
requires 'MIME::Decoder::UU';
requires 'MIME::Head';
requires 'MIME::Parser';
requires 'MIME::QuotedPrint';
requires 'MIME::Tools';
requires 'MIME::WordDecoder';
requires 'Net::CIDR';
requires 'Net::DNS';
requires 'Net::IP';
requires 'OLE::Storage_Lite';
requires 'Pod::Escapes';
requires 'Pod::Simple';
requires 'POSIX';
requires 'Scalar::Util';
requires 'Socket';
requires 'Storable';
requires 'Test::Harness';
requires 'Test::Pod';
requires 'Test::Simple';
requires 'Time::HiRes';
requires 'Time::localtime';
requires 'Sys::Hostname::Long';
requires 'Sys::SigAction';
requires 'Sys::Syslog';
requires 'Env';
requires 'Mail::SpamAssassin';

# MailScanner not required module (but nice to have)
requires 'bignum';
requires 'Data::Dump';
requires 'DB_File';
requires 'DBD::SQLite';
requires 'DBI';
requires 'Digest';
requires 'Encode::Detect';
requires 'Error';
requires 'ExtUtils::CBuilder';
requires 'ExtUtils::ParseXS';
requires 'Getopt::Long';
requires 'Inline';
requires 'IO::String';
requires 'IO::Zlib';
requires 'IP::Country';
requires 'Mail::SPF';
requires 'Mail::SPF::Query';
requires 'Module::Build';
requires 'Net::CIDR::Lite';
requires 'Net::DNS';
requires 'Net::LDAP';
requires 'Net::DNS::Resolver::Programmable';
requires 'NetAddr::IP';
requires 'Parse::RecDescent';
requires 'Test::Harness';
requires 'Test::Manifest';
requires 'Text::Balanced';
requires 'URI';
requires 'version';
requires 'IO::Compress::Bzip2';
requires 'Sendmail::PMilter';

# MailScanner additional spamassassin plugins
feature 'spamassassin-additional', 'Additional spamassassin plugins' => sub {
    requires 'Mail::SpamAssassin::Plugin::Rule2XSBody';
    requires 'Mail::SpamAssassin::Plugin::DCC';
    requires 'Mail::SpamAssassin::Plugin::Pyzor';
    requires 'Mail::SpamAssassin';

    # Error: Compilation failed in require
    # requires 'Mail::ClamAV';
};
